using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DeptEmpMgmt.Logic;
using System.Net.Mail;
using DeptEmpMgmt.Models;

namespace DeptEmpMgmt.Logic
{

    public class SendMail
    {
        public string GenerateRandomPassword()
        {
            Employee employee = new Employee();
            ApplicationDbContext context = new ApplicationDbContext();

            string PasswordLength = "12";
            string NewPassword = "";
            employee.RandomPassword = NewPassword;


            string allowedChars = "";
            allowedChars = "1,2,3,4,5,6,7,8,9,0";
            allowedChars += "A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,";
            allowedChars += "a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,";
            allowedChars += "~,!,@,#,$,%,^,&,*,+,?";



            char[] sep = { ',' };
            string[] arr = allowedChars.Split(sep);

            string IDString = "";
            string temp = "";


            Random rand = new Random();


            for (int i = 0; i < Convert.ToInt32(PasswordLength); i++)
            {
                temp = arr[rand.Next(0, arr.Length)];
                IDString += temp;
                NewPassword = IDString;
            }

            return NewPassword;
        }
        public void SendEmail(string emailBody)
        {
            string strNewPassword = GenerateRandomPassword().ToString();
            MailMessage mailMessage = new MailMessage("mothisanithaaloysius@gmail.com", "mothisanithaaloysius@gmail.com");

            mailMessage.Subject = "Autogenerated Password";
            mailMessage.Body = emailBody;

            mailMessage.IsBodyHtml = true;


            mailMessage.Body += "Your New Password <b>" + strNewPassword + "</b><br />";
            mailMessage.Body += "Please change the password by logging in.";
            mailMessage.Body += "<p>Click the following link to change your password:</p>";
            //  mail.Body += "<p>http://10.1.81.27/DeptEmpMgmt/passwordChangeThing/Default.aspx</P>";


            mailMessage.IsBodyHtml = true;
            SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
            smtp.Credentials = new System.Net.NetworkCredential("mothisanithaaloysius@gmail.com", "1.amazinggrace");


            smtp.EnableSsl = true;
            smtp.Send(mailMessage);
        }
    }
}
